---
# tasks that must be executed before all other tasks

- name: install base-devel
  community.general.pacman:
    name:
      - base-devel

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes

- name: install yay aur helper
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: makepkg
    name: yay-bin

- name: check if reboot is required due to kernel update
  shell: 'test "$(uname -r)" = "$(file /boot/vmlinuz-linux | cut -d\  -f9)"'
  register: kernel_check
  failed_when: kernel_check.rc == 127
  changed_when: "False"

- reboot:
  when: "ansible_connection != 'local' and kernel_check.rc != 0"