- name: install dotfile manager (yadm)
  become: true
  get_url:
    url: https://raw.githubusercontent.com/TheLocehiliosan/yadm/master/yadm
    dest: /usr/local/bin/yadm
    mode: '755'

- name: install transcrypt
  become: true
  get_url:
    url: https://raw.githubusercontent.com/elasticdog/transcrypt/main/transcrypt
    dest: /usr/local/bin/transcrypt
    mode: '755'

- name: clone dotfiles
  shell:
    creates: /home/ubuntu/.local/share/yadm/repo.git
    cmd: |
      yadm clone https://github.com/r-bar/dotfiles.git
      yadm reset --hard origin/master


- name: decrypt dotfiles
  shell: "yadm transcrypt -y -p '{{dotfiles_password}}'"
  when: 'dotfiles_password != ""'
