---
- name: install base packages
  apt:
    state: present
    update_cache: true
    name:
      - ansible
      - zsh
      - tmux
      - git
      - python3-pip
      - python3-venv
      - python-is-python3
      - fzf
      - curl
      - apt-transport-https

- name: install rust packages
  apt:
    state: present
    # FIXME: this is a bug in the debian rust build tools. Fixed in ubuntu 20.10
    # https://askubuntu.com/questions/1290262/unable-to-install-bat-error-trying-to-overwrite-usr-crates2-json-which
    dpkg_options: "force-confdef,force-confold,force-overwrite"
    name:
      - ripgrep
      - bat
      - fd-find
