---
- name: install docker packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - docker
      - docker-compose

- name: create docker configuration directory
  file:
    path: /etc/docker
    state: directory
    recurse: true
    owner: root
    group: root

- name: set docker daemon config
  vars:
    values:
      iptables: false
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ values | tojson }}"

- name: enable docker service
  # can fail when the host has not been restarted since last kernel update
  ignore_errors: true
  systemd:
    name: docker.service
    state: started
    enabled: yes