---
- name: install docker packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - docker
      - docker-compose

- name: add default user to docker group
  user:
    name: vagrant
    append: yes
    groups: [docker]

- name: 
  vars:
    values:
      iptables: false
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ values | tojson }}"

- name: enable docker service
  systemd:
    name: docker.service
    state: started
    enabled: yes