package_upgrade: true
# add packages required for running ansible-playbook
packages:
  - ansible
  - git

runcmd:
  - |
    cd /usr/local/share
    git clone https://github.com/r-bar/multipass-init.git
    cd multipass-init

    ansible-playbook -i inventory.yaml site.yaml
