---
- name: install docker pre-reqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker repo key
  shell:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    cmd: >-
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg
      | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: create apt repo file
  apt_repository:
    filename: docker
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu
      {{ansible_lsb.codename}} stable

- name: install docker
  apt:
    state: present
    name: [docker-ce, docker-ce-cli, containerd.io]
