---
- name: install dotfile manager
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: [yadm, transcrypt]

- name: clone dotfiles
  become: yes
  become_user: '{{primary_user}}'
  shell:
    creates: '/home/{{primary_user}}/.local/share/yadm/repo.git'
    cmd: |
      yadm clone https://github.com/r-bar/dotfiles.git
      yadm reset --hard origin/master

- name: decrypt dotfiles
  become: yes
  become_user: '{{primary_user}}'
  shell: "yadm transcrypt -y -p '{{dotfiles_password}}'"
  when: 'dotfiles_password != ""'